import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { QueryProvider } from '@/shared/providers/query-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html>
      <body className=" flex flex-col min-h-screen bg-zinc-50 text-zinc-950 antialiased">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
